# Site settings
title: SocialCOBizz
email: info@socialcobizz.com
description: > # this means to ignore newlines until "baseurl:"
 L'accélérateur des joint-ventures sociales
baseurl: "" # the subpath of your site, e.g. /blog/
url: "socialcobizz.com" # the base hostname & protocol for your site

# User setting
owner: SocialCOBizz
twitter_username: socialcobizz
# address:
#   - line:
#   - line:
#   # Feel free to add more lines here
# telephone:
copyright: SocialCOBizz

# API settings
# google_api_key:

# Build settings
markdown: kramdown